// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: com/along101/framework/raptor/proto/helloworld.proto
package com.along101.microservice.starter.raptor.proto;

import com.along101.raptor.annotation.RaptorField;
import com.along101.raptor.annotation.RaptorMessage;

@RaptorMessage(
        version = "version.0.1",
        protoFile = "helloworld"
)
public final class HelloRequest {
    private static final long serialVersionUID = 0L;

    @RaptorField(
            fieldType = "string",
            order = 1,
            name = "name"
    )
    private String name;


    public HelloRequest() {
    }

    public HelloRequest(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        if (name != null) builder.append(", name=").append(name);
        return builder.replace(0, 2, "HelloRequest{").append('}').toString();
    }
}
