// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: com/along101/framework/raptor/proto/helloworld.proto
package com.along101.microservice.starter.raptor.proto;

import com.along101.raptor.annotation.RaptorInterface;
import com.along101.raptor.annotation.RaptorMethod;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@RaptorInterface(
        appId = "123456",
        appName = "demo",
        version = "version.0.1",
        protoFile = "helloworld",
        library = "spring"
)
@RequestMapping
public interface Simple {

    @RequestMapping(
            path = "/raptor/sayHello",
            method = RequestMethod.GET
    )
    @RaptorMethod
    HelloReply getSayHello(HelloRequest request);

    @RequestMapping(
            path = "/raptor/sayHello",
            method = RequestMethod.POST
    )
    @RaptorMethod
    HelloReply postSayHello(HelloRequest request);
}
